server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: mindquest-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: ${DB_USERNAME:***}
    password: ${DB_PASSWORD:****}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - email
              - profile

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 3600000 # 1 hour
  refresh-expiration: 604800000 

app:
  admin-emails: admin@mindquest.com,sarah.chen@mindquest.com,mike.rodriguez@mindquest.com
    
  upload-dir: ${UPLOAD_DIR:./uploads}
  cors-allowed-origins: ${CORS_ORIGINS:http://localhost:3000,https://mindquest.vercel.app}

logging:
  level:
    com.mindquest: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE